// AUTO-GENERATED from German_Tech_Roadmap_2026_2028.xlsx
// Re-run scripts/extractRoadmap.py to regenerate after Excel changes

import type { TaskTrack } from '@/types'

export interface ExcelWeek {
  week:         number
  weekStart:    string
  phase:        string
  ml:           string
  cloud:        string
  backend:      string
  data:         string
  project:      string
  mern:         string
  german:       string
  tools:        string
  sundayReview: string
}

export interface ExcelMilestone {
  title:      string
  targetWeek: string
  targetDate: string
  category:   string
  why:        string
}

export const ROADMAP_WEEKS: ExcelWeek[] = [
  {
    week:         1,
    weekStart:    "10 May 2026",
    phase:        "Phase 0 \u2014 Uni + Foundation",
    ml:           "Python refresher: numpy, pandas, matplotlib (3 h/d)",
    cloud:        "Set up: Linux (WSL2), Git, VS Code, SSH keys",
    backend:      "\u2014  (uni phase: focus on Python basics)",
    data:         "\u2014",
    project:      "\u2014  (setup dev environment, GitHub profile)",
    mern:         "MERN audit: document current skill level",
    german:       "Arabic: final semester \u2014 focus on exams",
    tools:        "Notion setup, Anki install, Toggl Track",
    sundayReview: "Did I set up all tools? GitHub commit?",
  },
  {
    week:         2,
    weekStart:    "17 May 2026",
    phase:        "Phase 0 \u2014 Uni + Foundation",
    ml:           "Python OOP, virtual envs, Git workflow",
    cloud:        "Bash scripting fundamentals",
    backend:      "\u2014  (uni phase)",
    data:         "SQL refresher: joins, window functions, CTEs",
    project:      "\u2014  (Python portfolio starter repo)",
    mern:         "Polish existing MERN project for portfolio",
    german:       "Arabic: revision + grammar",
    tools:        "Obsidian vault setup + linking",
    sundayReview: "Is my Anki habit formed? 3 weeks to go.",
  },
  {
    week:         3,
    weekStart:    "24 May 2026",
    phase:        "Phase 0 \u2014 Uni + Foundation",
    ml:           "Math refresh: linear algebra (3Blue1Brown)",
    cloud:        "Docker: images, containers, volumes",
    backend:      "FastAPI: routing, Pydantic models",
    data:         "Advanced SQL: recursive CTEs, lateral joins",
    project:      "P1 planning: GDPR-RAG chatbot \u2014 write spec",
    mern:         "Freelance: set up Fiverr + Upwork profile",
    german:       "Arabic: exam prep",
    tools:        "VS Code: extensions (Python, Pylance, GitLens)",
    sundayReview: "Deep work habit: hitting 3 hrs/day?",
  },
  {
    week:         4,
    weekStart:    "31 May 2026",
    phase:        "Phase 0 \u2014 Uni + Foundation",
    ml:           "Math: probability & statistics for ML",
    cloud:        "Docker Compose: multi-service apps",
    backend:      "FastAPI: auth (JWT), middleware, background tasks",
    data:         "Data modeling: star schema, snowflake",
    project:      "P1: set up FastAPI backend skeleton",
    mern:         "Freelance: write 3 service proposals",
    german:       "Arabic: exam week",
    tools:        "GitHub profile: README + contribution graph",
    sundayReview: "MERN freelance profile live?",
  },
  {
    week:         5,
    weekStart:    "07 Jun 2026",
    phase:        "Phase 0 \u2014 Uni + Foundation",
    ml:           "Intro to ML: sklearn pipelines, train/test split",
    cloud:        "AWS free tier setup: EC2, S3, IAM basics",
    backend:      "PostgreSQL: schema design, indexes, transactions",
    data:         "dbt: models, tests, documentation",
    project:      "P1: document ingestion + chunking",
    mern:         "Freelance: land first small gig ($50\u2013200)",
    german:       "Arabic: done \u2014 begin German A1 immediately",
    tools:        "Forest app: 90-min deep work sessions",
    sundayReview: "First Fiverr/Upwork gig pitched?",
  },
  {
    week:         6,
    weekStart:    "14 Jun 2026",
    phase:        "Phase 0 \u2014 Uni + Foundation",
    ml:           "Supervised learning: regression & classification",
    cloud:        "AWS VPC, security groups, Route53",
    backend:      "Redis: caching, pub/sub, sessions",
    data:         "dbt: sources, seeds, snapshots",
    project:      "P1: vector DB (ChromaDB on Hetzner)",
    mern:         "Deliver gig #1 on time + ask for review",
    german:       "German A1: alphabet, pronunciation, Duolingo start",
    tools:        "Duolingo + Anki daily habit confirmed",
    sundayReview: "Project 1 spec written?",
  },
  {
    week:         7,
    weekStart:    "21 Jun 2026",
    phase:        "Phase 0 \u2014 Uni + Foundation",
    ml:           "Model evaluation: cross-val, confusion matrix, ROC",
    cloud:        "AWS RDS + managed services overview",
    backend:      "REST API best practices + OpenAPI docs",
    data:         "Airflow: DAGs, operators, sensors",
    project:      "P1: RAG query chain (LangChain)",
    mern:         "Build: MERN SaaS starter template (sell/use)",
    german:       "German A1: numbers, greetings, basic phrases",
    tools:        "Toggl: track all deep work hours",
    sundayReview: "German A1 started? Duolingo streak?",
  },
  {
    week:         8,
    weekStart:    "28 Jun 2026",
    phase:        "Phase 0 \u2014 Uni + Foundation",
    ml:           "Unsupervised: k-means, PCA \u2014 Anki deck started",
    cloud:        "AWS CLI + SDK (boto3) scripting",
    backend:      "Testing: pytest, test coverage",
    data:         "Airflow: XComs, templating, best practices",
    project:      "P1: add GDPR consent layer + data deletion",
    mern:         "Freelance: pitch 5 new clients",
    german:       "German A1: articles (der/die/das), plural forms",
    tools:        "Weekly review: Notion template first use",
    sundayReview: "8 weeks in \u2014 review Toggl hours vs target",
  },
  {
    week:         9,
    weekStart:    "05 Jul 2026",
    phase:        "Phase 1 \u2014 Python & ML Core",
    ml:           "PyTorch tensors & autograd",
    cloud:        "Terraform basics: providers, resources, state",
    backend:      "Java basics (German enterprise requirement)",
    data:         "Snowflake: architecture, virtual warehouses",
    project:      "P1: frontend (React) + deploy",
    mern:         "Build: React component library (reuse across gigs)",
    german:       "German A1: verbs (sein, haben), present tense",
    tools:        "Notion: set up weekly kanban (3 cols only)",
    sundayReview: "PyTorch basics solid?",
  },
  {
    week:         10,
    weekStart:    "12 Jul 2026",
    phase:        "Phase 1 \u2014 Python & ML Core",
    ml:           "Neural nets: forward + backward pass from scratch",
    cloud:        "Terraform: modules, variables, outputs",
    backend:      "Java OOP: classes, interfaces, generics",
    data:         "Snowflake: data sharing, time travel",
    project:      "P1: write README + blog post \u2192 PUBLISHED",
    mern:         "Freelance: deliver gig #2 \u2192 target $100\u2013300",
    german:       "German A1: word order (SVO) + W-questions",
    tools:        "Anki: ML deck growing (20 cards/day)",
    sundayReview: "P1 \u2014 is the RAG pipeline working?",
  },
  {
    week:         11,
    weekStart:    "19 Jul 2026",
    phase:        "Phase 1 \u2014 Python & ML Core",
    ml:           "Training loops, optimizers, learning rate schedulers",
    cloud:        "Terraform: deploy EC2 + S3 + RDS stack",
    backend:      "Spring Boot: controllers, services, repositories",
    data:         "Build: EV charging data pipeline (Project 5)",
    project:      "P2 planning: predictive maintenance spec",
    mern:         "Build: admin dashboard template (sell on Gumroad)",
    german:       "German A1: daily routine vocabulary (Anki deck)",
    tools:        "Toggl: check hours \u2014 aim 21 hrs/week deep work",
    sundayReview: "P2 started? Sensor data EDA done?",
  },
  {
    week:         12,
    weekStart:    "26 Jul 2026",
    phase:        "Phase 1 \u2014 Python & ML Core",
    ml:           "CNNs: conv layers, pooling, batch norm",
    cloud:        "GitHub Actions CI/CD: build \u2192 test \u2192 deploy",
    backend:      "Spring Boot: JPA + Hibernate",
    data:         "EV pipeline: dbt transformations",
    project:      "P2: synthetic sensor dataset generation",
    mern:         "Gumroad: publish + market dashboard template",
    german:       "German A1: modal verbs (k\u00f6nnen, m\u00fcssen, wollen)",
    tools:        "Obsidian: daily note habit",
    sundayReview: "First freelance income received?",
  },
  {
    week:         13,
    weekStart:    "02 Aug 2026",
    phase:        "Phase 1 \u2014 Python & ML Core",
    ml:           "Transfer learning: fine-tune ResNet on custom data",
    cloud:        "Kubernetes: pods, deployments, services (Minikube)",
    backend:      "Spring Security: OAuth2, JWT",
    data:         "EV pipeline: Airflow scheduling",
    project:      "P2: EDA + feature engineering",
    mern:         "Freelance: gig #3 \u2192 build momentum ($200\u2013500)",
    german:       "German A1: cases intro: Nominativ + Akkusativ",
    tools:        "GitHub: daily commit streak \u2014 start now",
    sundayReview: "Java Spring Boot setup done?",
  },
  {
    week:         14,
    weekStart:    "09 Aug 2026",
    phase:        "Phase 1 \u2014 Python & ML Core",
    ml:           "RNNs & LSTMs: sequence modelling",
    cloud:        "Kubernetes: ConfigMaps, Secrets, Ingress",
    backend:      "Spring Boot testing: JUnit 5, Mockito",
    data:         "EV pipeline: Grafana dashboard",
    project:      "P2: anomaly detection model (Isolation Forest)",
    mern:         "Build: MERN + AI integration (add ChatGPT to MERN)",
    german:       "German A1: prepositions + Dativ",
    tools:        "Notion: project tracker for all 6 projects",
    sundayReview: "Airflow DAG running?",
  },
  {
    week:         15,
    weekStart:    "16 Aug 2026",
    phase:        "Phase 1 \u2014 Python & ML Core",
    ml:           "Transformers: attention mechanism deep dive",
    cloud:        "Helm charts: package K8s apps",
    backend:      "Microservices patterns: API Gateway, service discovery",
    data:         "EV pipeline: deploy on Hetzner + document",
    project:      "P2: dashboard (Streamlit)",
    mern:         "Market: AI-powered MERN app to clients",
    german:       "German A1: complete A1 Anki deck (200 cards)",
    tools:        "Review: all tools working well?",
    sundayReview: "EV pipeline deployed?",
  },
  {
    week:         16,
    weekStart:    "23 Aug 2026",
    phase:        "Phase 1 \u2014 Python & ML Core",
    ml:           "HuggingFace Transformers: load, tokenize, infer",
    cloud:        "AWS EKS: managed Kubernetes",
    backend:      "Message queues: Kafka producer/consumer",
    data:         "Apache Kafka: streaming fundamentals",
    project:      "P2: deploy on AWS \u2192 PUBLISHED",
    mern:         "Freelance: aim for $300\u2013500/month total",
    german:       "German A2: past tense (Perfekt)",
    tools:        "Add: Jupyter notebooks to Obsidian links",
    sundayReview: "P1 + P2 + P5 all PUBLISHED?",
  },
  {
    week:         17,
    weekStart:    "30 Aug 2026",
    phase:        "Phase 2 \u2014 Cloud Basics",
    ml:           "HuggingFace datasets + trainer API",
    cloud:        "AWS EKS + Terraform (Project 3 infra)",
    backend:      "Kafka: topics, partitions, consumer groups",
    data:         "Kafka: schema registry, Avro",
    project:      "P3 planning: multi-tenant SaaS spec",
    mern:         "Build: SaaS boilerplate with auth + payments (Stripe)",
    german:       "German A2: Pr\u00e4teritum (haben/sein/modals)",
    tools:        "Add: Datadog free trial for Project 3",
    sundayReview: "Terraform deployed real infra?",
  },
  {
    week:         18,
    weekStart:    "06 Sep 2026",
    phase:        "Phase 2 \u2014 Cloud Basics",
    ml:           "Fine-tuning BERT for text classification",
    cloud:        "Observability: Prometheus + Grafana",
    backend:      "gRPC: protocol buffers, streaming",
    data:         "Apache Spark: DataFrames, SparkSQL",
    project:      "P3: IaC with Terraform (VPC, EKS, RDS)",
    mern:         "Sell boilerplate: Gumroad / LemonSqueezy",
    german:       "German A2: separable verbs",
    tools:        "Add: Terraform Cloud for state management",
    sundayReview: "CI/CD pipeline working end-to-end?",
  },
  {
    week:         19,
    weekStart:    "13 Sep 2026",
    phase:        "Phase 2 \u2014 Cloud Basics",
    ml:           "LoRA / QLoRA: parameter-efficient fine-tuning",
    cloud:        "Logging: ELK stack basics",
    backend:      "GraphQL with Spring Boot",
    data:         "Spark: performance tuning, caching",
    project:      "P3: CI/CD pipeline (GitHub Actions)",
    mern:         "Freelance: larger project ($500\u20131000)",
    german:       "German A2: subordinate clauses (dass, weil, wenn)",
    tools:        "Add: HuggingFace account + profile",
    sundayReview: "P3 SaaS infra live?",
  },
  {
    week:         20,
    weekStart:    "20 Sep 2026",
    phase:        "Phase 2 \u2014 Cloud Basics",
    ml:           "RAG architecture: embeddings + vector DBs",
    cloud:        "Datadog: APM, dashboards, alerts",
    backend:      "Database migrations: Flyway / Liquibase",
    data:         "Spark: streaming with Kafka",
    project:      "P3: multi-tenancy implementation",
    mern:         "Automate: client onboarding workflow",
    german:       "German A2: relative clauses",
    tools:        "Add: MLflow local server",
    sundayReview: "GDPR architecture understood deeply?",
  },
  {
    week:         21,
    weekStart:    "27 Sep 2026",
    phase:        "Phase 2 \u2014 Cloud Basics",
    ml:           "LangChain: chains, agents, memory",
    cloud:        "GDPR-compliant architecture on AWS (data residency)",
    backend:      "API versioning strategies",
    data:         "Delta Lake: ACID transactions on data lake",
    project:      "P3: observability (Datadog)",
    mern:         "Build: client-specific MERN + ML dashboard",
    german:       "German A2: adjective endings",
    tools:        "Review: GitHub streak \u2014 keep going",
    sundayReview: "Kafka producer/consumer working?",
  },
  {
    week:         22,
    weekStart:    "04 Oct 2026",
    phase:        "Phase 2 \u2014 Cloud Basics",
    ml:           "Build RAG chatbot on German docs (Project 1 start)",
    cloud:        "AWS Frankfurt region + Hetzner: German data sovereignty",
    backend:      "Rate limiting + circuit breakers",
    data:         "Apache Iceberg: table format",
    project:      "P3: load test + cost analysis \u2192 PUBLISHED",
    mern:         "Integrate RAG chatbot (Project 1) into MERN app",
    german:       "German A2: Genitiv case",
    tools:        "Review: Anki stats \u2014 retention rate >85%?",
    sundayReview: "RAG chatbot demo-able?",
  },
  {
    week:         23,
    weekStart:    "11 Oct 2026",
    phase:        "Phase 2 \u2014 Cloud Basics",
    ml:           "MLflow: experiment tracking, model registry",
    cloud:        "Cost optimisation: spot instances, reserved",
    backend:      "Distributed tracing: OpenTelemetry",
    data:         "Data lakehouse architecture",
    project:      "P5 planning: EV charging pipeline spec",
    mern:         "Sell: AI chatbot integration service to SMBs",
    german:       "German A2: tech vocabulary (Computer, Software, Daten)",
    tools:        "Review: Toggl \u2014 is deep work hitting 3 hrs/day?",
    sundayReview: "SAA-C03 study started?",
  },
  {
    week:         24,
    weekStart:    "18 Oct 2026",
    phase:        "Phase 2 \u2014 Cloud Basics",
    ml:           "GDPR-compliant ML data handling",
    cloud:        "Security: IAM policies, least privilege, AWS GuardDuty",
    backend:      "Performance: JVM tuning, profiling",
    data:         "SAP data extraction: Python pyRFC",
    project:      "P5: Airflow + dbt setup",
    mern:         "Freelance: target $500\u2013800/month",
    german:       "German A2: complete A2 Anki deck (400 cards)",
    tools:        "Add: LinkedIn premium (1 month trial)",
    sundayReview: "German A2 reached? Anki 400 cards done?",
  },
  {
    week:         25,
    weekStart:    "25 Oct 2026",
    phase:        "Phase 2 \u2014 Cloud Basics",
    ml:           "Model serving: FastAPI + Docker",
    cloud:        "AWS Solutions Architect study \u2014 begin",
    backend:      "System design: scalable REST APIs",
    data:         "SAP \u2192 Snowflake pipeline",
    project:      "P5: data ingestion from open API",
    mern:         "Build: multi-client CMS (reusable)",
    german:       "German B1: Konjunktiv II (w\u00fcrde, k\u00f6nnte, w\u00e4re)",
    tools:        "Review: Notion \u2014 all 6 projects tracked?",
    sundayReview: "Snowflake account set up?",
  },
  {
    week:         26,
    weekStart:    "01 Nov 2026",
    phase:        "Phase 3 \u2014 First Projects",
    ml:           "Time-series fundamentals (for Project 2)",
    cloud:        "SAA-C03: VPC deep dive",
    backend:      "Build: backend for Project 1 (RAG chatbot API)",
    data:         "Great Expectations: data quality testing",
    project:      "P5: dbt transformations + tests",
    mern:         "Freelance: raise rates ($30\u201350/hr)",
    german:       "German B1: Passiv voice",
    tools:        "Add: Upwork/Fiverr for MERN freelance",
    sundayReview: "SAA-C03 exam scheduled?",
  },
  {
    week:         27,
    weekStart:    "08 Nov 2026",
    phase:        "Phase 3 \u2014 First Projects",
    ml:           "Anomaly detection: isolation forest, autoencoders",
    cloud:        "SAA-C03: compute (EC2, Lambda, ECS)",
    backend:      "Build: auth service with GDPR consent management",
    data:         "Data contracts: schema enforcement",
    project:      "P5: Grafana dashboard \u2192 PUBLISHED",
    mern:         "Build: German-market landing page template",
    german:       "German B1: Infinitivkonstruktionen (um\u2026zu)",
    tools:        "Add: Gumroad account for digital products",
    sundayReview: "P4 (LLM fine-tune) dataset ready?",
  },
  {
    week:         28,
    weekStart:    "15 Nov 2026",
    phase:        "Phase 3 \u2014 First Projects",
    ml:           "Sensor data preprocessing pipeline",
    cloud:        "SAA-C03: storage (S3, EFS, FSx)",
    backend:      "Build: event-driven order service (Kafka)",
    data:         "Data lineage: OpenLineage",
    project:      "P4 planning: LLM fine-tune spec",
    mern:         "Market to German Mittelstand via LinkedIn",
    german:       "German B1: business German (Bewerbung = job application)",
    tools:        "Review: Anki retention + add missed concepts",
    sundayReview: "Freelance income: $300+/month?",
  },
  {
    week:         29,
    weekStart:    "22 Nov 2026",
    phase:        "Phase 3 \u2014 First Projects",
    ml:           "Predictive maintenance model training (Project 2)",
    cloud:        "SAA-C03: databases",
    backend:      "Build: multi-tenant data isolation layer",
    data:         "Data governance: GDPR in data platform",
    project:      "P4: dataset preparation (German domain)",
    mern:         "Freelance: target \u20ac600/month",
    german:       "German B1: tech interview phrases",
    tools:        "Review: GitHub \u2014 are projects getting stars?",
    sundayReview: "P4 LoRA run completed?",
  },
  {
    week:         30,
    weekStart:    "29 Nov 2026",
    phase:        "Phase 3 \u2014 First Projects",
    ml:           "Model evaluation & deployment (Project 2 done)",
    cloud:        "SAA-C03: practice exam 1",
    backend:      "Code review + refactor all backend code",
    data:         "Build: GDPR-compliant data platform (Project 6 start)",
    project:      "P4: LoRA fine-tuning run",
    mern:         "Build: MERN + data viz dashboard (use D3/Recharts)",
    german:       "German B1: practice speaking (italki tutor 1\u00d7/week)",
    tools:        "Review: MERN income tracking in Notion",
    sundayReview: "P4 on HuggingFace Hub?  6 PROJECTS DONE!",
  },
  {
    week:         31,
    weekStart:    "06 Dec 2026",
    phase:        "Phase 3 \u2014 First Projects",
    ml:           "Revisit: LLM architectures (GPT, T5, Mistral)",
    cloud:        "SAA-C03: practice exam 2 + review weak areas",
    backend:      "Kotlin basics (preferred for new Java projects)",
    data:         "Data platform: ingestion layer",
    project:      "P4: evaluation + benchmark",
    mern:         "Integrate Project 5 (EV data) into MERN dashboard",
    german:       "German B1: Goethe B1 practice test #1",
    tools:        "Tools audit: remove anything not being used",
    sundayReview: "AWS SAA exam sat?",
  },
  {
    week:         32,
    weekStart:    "13 Dec 2026",
    phase:        "Phase 3 \u2014 First Projects",
    ml:           "Prompt engineering & system prompts",
    cloud:        "AWS SAA Exam (schedule this week)",
    backend:      "Kotlin coroutines + Flow",
    data:         "Data platform: transformation layer (dbt)",
    project:      "P4: HuggingFace publish \u2192 PUBLISHED",
    mern:         "Sell dashboard service: energy / logistics clients",
    german:       "German B1: Goethe B1 practice test #2 + review",
    tools:        "Tools: set up German learning tracker in Notion",
    sundayReview: "Azure AZ-900 started?",
  },
  {
    week:         33,
    weekStart:    "20 Dec 2026",
    phase:        "Phase 3 \u2014 First Projects",
    ml:           "Open-source LLM: Mistral local inference",
    cloud:        "Azure: AZ-900 fundamentals (German corps use Azure)",
    backend:      "Ktor: Kotlin web framework",
    data:         "Data platform: serving layer + BI",
    project:      "P6 planning: GDPR data platform spec",
    mern:         "Freelance: \u20ac700\u20131000/month target",
    german:       "Goethe B1 Exam (register + sit)",
    tools:        "Add: italki account for German tutors",
    sundayReview: "German B1 exam registered?",
  },
  {
    week:         34,
    weekStart:    "27 Dec 2026",
    phase:        "Phase 3 \u2014 First Projects",
    ml:           "Fine-tune Mistral on German domain (Project 4 start)",
    cloud:        "Azure: AKS, Azure ML, DevOps pipelines",
    backend:      "Go basics (Berlin startup ecosystem)",
    data:         "Data platform: data quality checks",
    project:      "P6: data ingestion layer",
    mern:         "Build: MERN + ML inference API client",
    german:       "German B2: advanced grammar review",
    tools:        "Add: Heise Online RSS feed",
    sundayReview: "Spring Boot microservices pattern implemented?",
  },
  {
    week:         35,
    weekStart:    "03 Jan 2027",
    phase:        "Phase 3 \u2014 First Projects",
    ml:           "LoRA training run + evaluation metrics",
    cloud:        "Azure: AZ-104 study start",
    backend:      "Go: goroutines, channels, REST API",
    data:         "Data platform: documentation + deploy",
    project:      "P6: dbt + quality checks",
    mern:         "Market: AI-powered web apps to German SMBs",
    german:       "German B2: complex sentence structures",
    tools:        "Review: all tools \u2014 Q4 2026 audit",
    sundayReview: "Freelance income: $500+/month?",
  },
  {
    week:         36,
    weekStart:    "10 Jan 2027",
    phase:        "Phase 4 \u2014 ML Depth",
    ml:           "Publish fine-tuned model to HuggingFace Hub",
    cloud:        "AZ-104: identity & governance",
    backend:      "System design: DDIA chapters 1\u20134",
    data:         "Azure Data Factory: pipelines",
    project:      "P6: data catalog + lineage",
    mern:         "Freelance: raise hourly rate to \u20ac40\u201360/hr",
    german:       "German B2: technical writing in German",
    tools:        "Add: XING profile (German LinkedIn)",
    sundayReview: "AZ-104 study started?",
  },
  {
    week:         37,
    weekStart:    "17 Jan 2027",
    phase:        "Phase 4 \u2014 ML Depth",
    ml:           "MLOps: CI/CD for ML models",
    cloud:        "AZ-104: storage + compute",
    backend:      "System design: DDIA chapters 5\u20137 (replication)",
    data:         "Azure Synapse Analytics",
    project:      "P6: GDPR audit trail \u2192 PUBLISHED",
    mern:         "Systemize: standard contract + invoice templates",
    german:       "German B2: German tech news reading (Heise Online)",
    tools:        "Add: dev.to account for blog posts",
    sundayReview: "DDIA chapters 1\u20134 read?",
  },
  {
    week:         38,
    weekStart:    "24 Jan 2027",
    phase:        "Phase 4 \u2014 ML Depth",
    ml:           "Monitoring: data drift, concept drift",
    cloud:        "AZ-104: networking",
    backend:      "System design: DDIA chapters 8\u20139 (distributed)",
    data:         "Azure Data Engineer cert (DP-203) study",
    project:      "OSS: first PR to open-source project",
    mern:         "Systemize: project delivery checklist",
    german:       "German B2: podcasts (Langsam gesprochene Nachrichten)",
    tools:        "Add: Medium account",
    sundayReview: "OSS first PR merged?",
  },
  {
    week:         39,
    weekStart:    "31 Jan 2027",
    phase:        "Phase 4 \u2014 ML Depth",
    ml:           "A/B testing for ML models",
    cloud:        "AZ-104: monitoring + practice exam",
    backend:      "System design: DDIA chapters 10\u201312 (derived data)",
    data:         "DP-203: data storage",
    project:      "OSS: second contribution",
    mern:         "Systemize: client communication templates",
    german:       "German B2: workplace German (meetings, emails)",
    tools:        "Add: Hashnode for tech blog",
    sundayReview: "Blog: 2 posts published?",
  },
  {
    week:         40,
    weekStart:    "07 Feb 2027",
    phase:        "Phase 4 \u2014 ML Depth",
    ml:           "Feature stores: Feast basics",
    cloud:        "Azure AZ-104 Exam",
    backend:      "Mock system design: design Twitter",
    data:         "DP-203: data processing",
    project:      "All 6 projects: update READMEs with metrics",
    mern:         "Freelance: \u20ac1000/month target \u2192 financial cushion",
    german:       "German B2: German CV + Anschreiben (cover letter)",
    tools:        "Review: blog posts published \u2014 target: 2 done",
    sundayReview: "Freelance: $1000/month?  MAJOR MILESTONE",
  },
  {
    week:         41,
    weekStart:    "14 Feb 2027",
    phase:        "Phase 4 \u2014 ML Depth",
    ml:           "Advanced RAG: re-ranking, hybrid search",
    cloud:        "CKA prep: K8s cluster setup from scratch",
    backend:      "Mock system design: design YouTube",
    data:         "DP-203: data security + practice exam",
    project:      "Blog post: ML lessons from Project 2",
    mern:         "Build: Next.js 14 portfolio for German market",
    german:       "German B2: practice job interview in German",
    tools:        "Add: LeetCode account + streak",
    sundayReview: "CKA prep started?",
  },
  {
    week:         42,
    weekStart:    "21 Feb 2027",
    phase:        "Phase 4 \u2014 ML Depth",
    ml:           "Multi-modal: CLIP, image+text pipelines",
    cloud:        "CKA prep: workloads & scheduling",
    backend:      "Mock system design: design Booking.com (German)",
    data:         "DP-203 Exam",
    project:      "Blog post: GDPR architecture decisions",
    mern:         "SEO: German-keyword optimized landing page",
    german:       "German B2: practice test #1",
    tools:        "Review: Notion \u2014 phases on track?",
    sundayReview: "German B1 exam SAT?",
  },
  {
    week:         43,
    weekStart:    "28 Feb 2027",
    phase:        "Phase 4 \u2014 ML Depth",
    ml:           "Reinforcement learning fundamentals",
    cloud:        "CKA prep: networking (CNI, DNS)",
    backend:      "Leetcode: arrays & strings (30 mins/day)",
    data:         "Databricks: unified analytics",
    project:      "Add: unit tests to all projects",
    mern:         "Network: join German developer Slack communities",
    german:       "German B2: practice test #2 + review",
    tools:        "Review: GitHub contributions heatmap",
    sundayReview: "Leetcode: 50 problems done?",
  },
  {
    week:         44,
    weekStart:    "07 Mar 2027",
    phase:        "Phase 4 \u2014 ML Depth",
    ml:           "RL from human feedback (RLHF) concepts",
    cloud:        "CKA prep: storage (PV, PVC)",
    backend:      "Leetcode: trees & graphs",
    data:         "Databricks: MLflow integration",
    project:      "Add: integration tests to 2 projects",
    mern:         "Network: LinkedIn connect with 20 German devs",
    german:       "Goethe B2 Exam (register + sit)",
    tools:        "Review: HuggingFace profile",
    sundayReview: "DP-203 study started?",
  },
  {
    week:         45,
    weekStart:    "14 Mar 2027",
    phase:        "Phase 4 \u2014 ML Depth",
    ml:           "Capstone: end-to-end MLOps pipeline",
    cloud:        "CKA prep: troubleshooting + practice exam",
    backend:      "Leetcode: dynamic programming",
    data:         "Databricks: Delta Live Tables",
    project:      "Portfolio site: personal site with projects",
    mern:         "Freelance: \u20ac1200/month",
    german:       "German: maintain with 20 Anki cards/day",
    tools:        "Tools: half-year audit \u2014 Q1 2027",
    sundayReview: "Portfolio site live?",
  },
  {
    week:         46,
    weekStart:    "21 Mar 2027",
    phase:        "Phase 4 \u2014 ML Depth",
    ml:           "Review all ML concepts \u2014 update Anki deck",
    cloud:        "CKA Exam",
    backend:      "Leetcode: hard problems \u00d7 5",
    data:         "dbt advanced: macros, packages, exposures",
    project:      "Portfolio: German-language project description",
    mern:         "Build: MERN + authentication (Clerk / Auth0)",
    german:       "German: listen to German tech podcasts daily",
    tools:        "Add: Obsidian publish (optional \u2014 public notes)",
    sundayReview: "CKA exam SAT?",
  },
  {
    week:         47,
    weekStart:    "28 Mar 2027",
    phase:        "Phase 5 \u2014 Data Engineering",
    ml:           "Spark: RDDs, DataFrames, SparkSQL",
    cloud:        "Service mesh: Istio basics",
    backend:      "SAP integration: RFC, BAPIs, IDoc basics",
    data:         "Data mesh principles",
    project:      "P7 planning: German-language AI product",
    mern:         "Add AI features to existing client projects",
    german:       "German: read 1 German tech article/day (Heise)",
    tools:        "Review: LinkedIn SSI score",
    sundayReview: "German B2 study started?",
  },
  {
    week:         48,
    weekStart:    "04 Apr 2027",
    phase:        "Phase 5 \u2014 Data Engineering",
    ml:           "Spark ML: scalable training",
    cloud:        "GitOps: ArgoCD",
    backend:      "SAP REST APIs: oData services",
    data:         "Data product thinking",
    project:      "P7: German NLP model + API",
    mern:         "Upsell: add AI features at \u20ac200\u2013500 extra",
    german:       "German: italki tutor 2\u00d7/week",
    tools:        "Review: Toggl hours \u2014 21+ hrs deep work/week?",
    sundayReview: "Databricks account set up?",
  },
  {
    week:         49,
    weekStart:    "11 Apr 2027",
    phase:        "Phase 5 \u2014 Data Engineering",
    ml:           "Stream processing: Kafka + Spark Streaming",
    cloud:        "Secrets management: Vault",
    backend:      "Legacy modernisation patterns",
    data:         "Reverse ETL: census, hightouch",
    project:      "P7: deploy + blog post in English & German",
    mern:         "Freelance: \u20ac1500/month",
    german:       "German: watch German TV (Dark, How to Sell Drugs)",
    tools:        "Review: German Anki retention",
    sundayReview: "Freelance: \u20ac1500/month?",
  },
  {
    week:         50,
    weekStart:    "18 Apr 2027",
    phase:        "Phase 5 \u2014 Data Engineering",
    ml:           "Real-time ML inference on streams",
    cloud:        "SRE principles: SLI, SLO, error budgets",
    backend:      "Event sourcing + CQRS pattern",
    data:         "Real-time analytics: ClickHouse",
    project:      "Conference: submit abstract to PyData Berlin",
    mern:         "Productize: offer fixed-price AI integration packages",
    german:       "German: join German-speaking Discord",
    tools:        "Review: all 6 projects \u2014 GitHub stars?",
    sundayReview: "PyData Berlin talk submitted?",
  },
  {
    week:         51,
    weekStart:    "25 Apr 2027",
    phase:        "Phase 5 \u2014 Data Engineering",
    ml:           "Feature engineering at scale",
    cloud:        "Chaos engineering: Chaos Monkey concepts",
    backend:      "Domain-driven design (DDD) basics",
    data:         "Feature engineering for ML pipelines",
    project:      "Conference: prepare talk slides",
    mern:         "Market: cold email 20 German SMBs",
    german:       "German: write LinkedIn post in German",
    tools:        "Add: portfolio site analytics (Plausible)",
    sundayReview: "Leetcode: 100 problems done?",
  },
  {
    week:         52,
    weekStart:    "02 May 2027",
    phase:        "Phase 5 \u2014 Data Engineering",
    ml:           "ML for tabular data: XGBoost, LightGBM",
    cloud:        "Multi-cloud strategy patterns",
    backend:      "Hexagonal architecture",
    data:         "Feature store: Feast implementation",
    project:      "All projects: add Docker Compose setup",
    mern:         "Market: cold email 20 more",
    german:       "German: translate 1 project README to German",
    tools:        "Review: blog traffic",
    sundayReview: "All projects Docker Compose?",
  },
  {
    week:         53,
    weekStart:    "09 May 2027",
    phase:        "Phase 5 \u2014 Data Engineering",
    ml:           "Hyperparameter tuning: Optuna",
    cloud:        "FinOps: cloud cost governance",
    backend:      "Clean code + SOLID principles deep dive",
    data:         "ML feature pipelines with Spark",
    project:      "All projects: add Terraform deployment",
    mern:         "Freelance: \u20ac1800/month",
    german:       "German: practice technical explanations auf Deutsch",
    tools:        "Review: freelance income vs target",
    sundayReview: "All projects Terraform deploy?",
  },
  {
    week:         54,
    weekStart:    "16 May 2027",
    phase:        "Phase 5 \u2014 Data Engineering",
    ml:           "Interpretability: SHAP, LIME",
    cloud:        "Platform engineering: Internal Dev Portals",
    backend:      "Code quality: SonarQube, static analysis",
    data:         "Data infrastructure cost optimisation",
    project:      "All projects: add observability",
    mern:         "Build: German-language AI chatbot SaaS (B2B)",
    german:       "German: describe system architecture in German",
    tools:        "Review: certs achieved vs plan",
    sundayReview: "AWS DevOps Pro study started?",
  },
  {
    week:         55,
    weekStart:    "23 May 2027",
    phase:        "Phase 5 \u2014 Data Engineering",
    ml:           "Fairness & bias in ML",
    cloud:        "Infrastructure as Product mindset",
    backend:      "Tech debt management strategies",
    data:         "Data platform reliability: SLOs",
    project:      "All projects: cost analysis added",
    mern:         "SaaS: MVP launch + first paying user",
    german:       "German: write blog post in German",
    tools:        "Tools: Q2 2027 audit",
    sundayReview: "SaaS MVP launched?",
  },
  {
    week:         56,
    weekStart:    "30 May 2027",
    phase:        "Phase 5 \u2014 Data Engineering",
    ml:           "ML system design patterns",
    cloud:        "Cloud-native security: SAST, DAST, SBOM",
    backend:      "API security: OWASP Top 10",
    data:         "Data team collaboration: DataHub catalog",
    project:      "Portfolio audit: every project has README, demo, blog",
    mern:         "SaaS: iterate on feedback",
    german:       "German: Anki 20 cards + 1 podcast",
    tools:        "Review: total learning hours logged (Toggl)",
    sundayReview: "Freelance: \u20ac2000/month?",
  },
  {
    week:         57,
    weekStart:    "06 Jun 2027",
    phase:        "Phase 5 \u2014 Data Engineering",
    ml:           "Review + update portfolio ML projects",
    cloud:        "ISO 27001 + BSI IT-Grundschutz overview",
    backend:      "Build: SAP integration connector (Project 5)",
    data:         "Review all data projects + update docs",
    project:      "LinkedIn: case study for each project",
    mern:         "Freelance + SaaS: \u20ac2000/month combined",
    german:       "German: Anki 20 cards + 1 article",
    tools:        "Review: GitHub contributions \u2014 365 day streak?",
    sundayReview: "German B2 exam registered?",
  },
  {
    week:         58,
    weekStart:    "13 Jun 2027",
    phase:        "Phase 6 \u2014 Backend Mastery",
    ml:           "Bayesian ML basics",
    cloud:        "GDPR technical controls deep dive",
    backend:      "Build: real-time data pipeline API",
    data:         "Advanced Spark: custom UDFs",
    project:      "GitHub stars goal: 50+ on top project",
    mern:         "Delegate: simple gigs to junior devs (scale)",
    german:       "German: Anki 20 cards + 1 podcast",
    tools:        "Review: job application tracker in Notion",
    sundayReview: "Advanced Spark UDFs working?",
  },
  {
    week:         59,
    weekStart:    "20 Jun 2027",
    phase:        "Phase 6 \u2014 Backend Mastery",
    ml:           "Graph neural networks intro",
    cloud:        "Zero-trust architecture",
    backend:      "Build: multi-tenant SaaS backend (Project 3)",
    data:         "Streaming ML: online learning",
    project:      "OSS: major contribution (new feature)",
    mern:         "Focus: German enterprise clients (higher rates)",
    german:       "German: German startup podcast (Gr\u00fcnderszene)",
    tools:        "Review: interview pipeline",
    sundayReview: "Streaming ML pipeline built?",
  },
  {
    week:         60,
    weekStart:    "27 Jun 2027",
    phase:        "Phase 6 \u2014 Backend Mastery",
    ml:           "Advanced NLP: NER, relation extraction",
    cloud:        "Cloud resume challenge (public portfolio)",
    backend:      "API gateway + rate limiting implementation",
    data:         "Build: real-time ML feature pipeline",
    project:      "OSS: PR merged into significant project",
    mern:         "German enterprise: target \u20ac80\u2013100/hr Freiberufler",
    german:       "German: network in German on XING",
    tools:        "Review: German level \u2014 B1 done?",
    sundayReview: "German B2 exam SAT?",
  },
  {
    week:         61,
    weekStart:    "04 Jul 2027",
    phase:        "Phase 6 \u2014 Backend Mastery",
    ml:           "LLM agents: tool use, ReAct pattern",
    cloud:        "AWS Advanced Networking study",
    backend:      "Backend + ML integration: serving predictions",
    data:         "Data engineering for LLMs: pre-training data",
    project:      "Build: new mini-project from Arxiv paper",
    mern:         "Register: Freiberufler status in Germany (prep)",
    german:       "German: practice cold email auf Deutsch",
    tools:        "Review: MERN income runway",
    sundayReview: "Kubeflow pipeline running?",
  },
  {
    week:         62,
    weekStart:    "11 Jul 2027",
    phase:        "Phase 6 \u2014 Backend Mastery",
    ml:           "Multi-agent systems",
    cloud:        "AWS DevOps Professional study",
    backend:      "Backend for RAG: document ingestion API",
    data:         "Data engineering for RAG: vector pipeline",
    project:      "Mini-project: blog post",
    mern:         "Legal: understand Scheinselbstst\u00e4ndigkeit rules",
    german:       "German: German workplace culture study",
    tools:        "Review: portfolio completeness",
    sundayReview: "Freiberufler registration researched?",
  },
  {
    week:         63,
    weekStart:    "18 Jul 2027",
    phase:        "Phase 6 \u2014 Backend Mastery",
    ml:           "LLM evaluation: benchmarks, human eval",
    cloud:        "AWS DevOps Pro practice exam",
    backend:      "Backend: async job processing system",
    data:         "Advanced dbt: unit tests",
    project:      "Collaboration: find German dev partner on GitHub",
    mern:         "Freelance: \u20ac2500/month target",
    german:       "German: P\u00fcnktlichkeit, Direktheit, formality norms",
    tools:        "Tools: Q3 2027 audit",
    sundayReview: "Freelance: \u20ac2500/month?",
  },
  {
    week:         64,
    weekStart:    "25 Jul 2027",
    phase:        "Phase 6 \u2014 Backend Mastery",
    ml:           "Production LLM: latency, cost optimisation",
    cloud:        "AWS DevOps Pro Exam (schedule)",
    backend:      "Backend: webhooks + event streaming",
    data:         "Benchmark: Spark vs Flink",
    project:      "Collaboration: joint project or review",
    mern:         "Portfolio: add German case studies",
    german:       "German: italki conversation practice",
    tools:        "Add: Cal.com for interview scheduling",
    sundayReview: "All projects updated with observability?",
  },
  {
    week:         65,
    weekStart:    "01 Aug 2027",
    phase:        "Phase 6 \u2014 Backend Mastery",
    ml:           "ML platform design (Uber Michelangelo style)",
    cloud:        "Review all cloud certs achieved",
    backend:      "Backend: GDPR right-to-erasure endpoint",
    data:         "Data engineering blog post",
    project:      "All projects: performance benchmarks added",
    mern:         "LinkedIn: German-language content posts",
    german:       "German: Anki + podcast",
    tools:        "Review: all certs on LinkedIn",
    sundayReview: "All certs on LinkedIn?",
  },
  {
    week:         66,
    weekStart:    "08 Aug 2027",
    phase:        "Phase 6 \u2014 Backend Mastery",
    ml:           "Read: Designing ML Systems (Chip Huyen) ch 1\u20134",
    cloud:        "Design: GDPR-first multi-tenant SaaS (cloud arch doc)",
    backend:      "Code review: all 6 projects backend",
    data:         "Mock data engineering interview",
    project:      "All projects: security review",
    mern:         "XING: German professional network profile",
    german:       "German: Anki + article",
    tools:        "Review: projects on personal site",
    sundayReview: "XING profile complete?",
  },
  {
    week:         67,
    weekStart:    "15 Aug 2027",
    phase:        "Phase 6 \u2014 Backend Mastery",
    ml:           "Read: Designing ML Systems ch 5\u20138",
    cloud:        "Build: cloud architecture diagram for portfolio",
    backend:      "Write RFC: backend architecture decisions",
    data:         "Mock: design a data platform for Bosch",
    project:      "All projects: GDPR compliance checklist",
    mern:         "Freelance: \u20ac3000/month",
    german:       "German: Anki + podcast",
    tools:        "Review: GitHub profile README",
    sundayReview: "Freelance: \u20ac3000/month?",
  },
  {
    week:         68,
    weekStart:    "22 Aug 2027",
    phase:        "Phase 6 \u2014 Backend Mastery",
    ml:           "Read: Designing ML Systems ch 9\u201312",
    cloud:        "Write ADR: cloud platform decision",
    backend:      "Write ADR: database selection",
    data:         "Mock: streaming pipeline design",
    project:      "All projects: cost optimisation applied",
    mern:         "Reduce MERN hours as ML job approaches",
    german:       "German: Anki + article",
    tools:        "Review: XING + LinkedIn both updated",
    sundayReview: "Blog: 5+ posts published?",
  },
  {
    week:         69,
    weekStart:    "29 Aug 2027",
    phase:        "Phase 6 \u2014 Backend Mastery",
    ml:           "Mock ML system design interview",
    cloud:        "Mock cloud architect interview",
    backend:      "Mock coding interview: Java/Python",
    data:         "Data portfolio: all projects documented",
    project:      "Portfolio v2: redesigned personal site",
    mern:         "Transition plan: freelance \u2192 full-time German job",
    german:       "German: Anki + podcast",
    tools:        "Review: German B2 on track?",
    sundayReview: "OSS: 2+ PRs merged?",
  },
  {
    week:         70,
    weekStart:    "05 Sep 2027",
    phase:        "Phase 6 \u2014 Backend Mastery",
    ml:           "Mock ML system design interview #2",
    cloud:        "Mock cloud + system design interview",
    backend:      "Mock system design \u00d7 2",
    data:         "Open source: contribute to dbt-core or Airflow",
    project:      "Portfolio: add video demos",
    mern:         "Freelance: maintain \u20ac2000/month minimal effort",
    german:       "German: mock job interview auf Deutsch",
    tools:        "Tools: Q4 2027 audit \u2014 are you on track?",
    sundayReview: "HALFWAY \u2014 70 weeks done! Celebrate + big review",
  },
  {
    week:         71,
    weekStart:    "12 Sep 2027",
    phase:        "Phase 7 \u2014 Senior Projects",
    ml:           "Advanced fine-tuning: DPO, PPO",
    cloud:        "Advanced K8s: operators, CRDs",
    backend:      "Advanced: reactive programming (WebFlux)",
    data:         "Advanced: distributed query engines",
    project:      "Blog: publish on dev.to + LinkedIn",
    mern:         "Automate: recurring client retainer setup",
    german:       "German: C1 prep \u2014 advanced grammar",
    tools:        "Add: Notion job tracker (company, role, status)",
    sundayReview: "Advanced K8s operators working?",
  },
  {
    week:         72,
    weekStart:    "19 Sep 2027",
    phase:        "Phase 7 \u2014 Senior Projects",
    ml:           "LLM security: prompt injection, jailbreaks",
    cloud:        "Advanced K8s: multi-cluster federation",
    backend:      "Advanced: database internals (B-trees, WAL)",
    data:         "Advanced: data compression & encoding",
    project:      "Blog: cross-post on Medium",
    mern:         "Hand off small clients to trusted junior dev",
    german:       "German: C1 \u2014 academic/technical writing",
    tools:        "Review: application \u2192 interview conversion rate",
    sundayReview: "C1 German prep started?",
  },
  {
    week:         73,
    weekStart:    "26 Sep 2027",
    phase:        "Phase 7 \u2014 Senior Projects",
    ml:           "Multimodal LLMs: GPT-4V style architectures",
    cloud:        "eBPF: observability at kernel level",
    backend:      "Advanced: distributed consensus (Raft)",
    data:         "Advanced: storage systems internals",
    project:      "Tech talk: local Python meetup (Berlin/Hamburg prep)",
    mern:         "Focus: only high-value German enterprise gigs",
    german:       "German: C1 \u2014 formal presentations",
    tools:        "Review: referrals from German network",
    sundayReview: "Load tests on all projects?",
  },
  {
    week:         74,
    weekStart:    "03 Oct 2027",
    phase:        "Phase 7 \u2014 Senior Projects",
    ml:           "Diffusion models: DDPM, Stable Diffusion",
    cloud:        "WebAssembly on the edge",
    backend:      "Advanced: CRDTs for conflict resolution",
    data:         "Advanced: column-oriented databases",
    project:      "Apply to speak at PyData 2027",
    mern:         "MERN: \u20ac2000/month passive-ish income",
    german:       "German: C1 \u2014 practice test",
    tools:        "Review: cover letter effectiveness",
    sundayReview: "30 job applications sent?",
  },
  {
    week:         75,
    weekStart:    "10 Oct 2027",
    phase:        "Phase 7 \u2014 Senior Projects",
    ml:           "AI agents: LangGraph, AutoGen",
    cloud:        "Serverless: AWS Lambda patterns",
    backend:      "Performance engineering: load testing (k6)",
    data:         "Performance: 1B row challenge",
    project:      "All projects: final architecture diagrams",
    mern:         "Save: 3-month Germany relocation fund",
    german:       "German: C1 Exam prep final",
    tools:        "Review: all tools for job hunt phase",
    sundayReview: "Relocation savings: 3 months runway?",
  },
  {
    week:         76,
    weekStart:    "17 Oct 2027",
    phase:        "Phase 7 \u2014 Senior Projects",
    ml:           "German-language NLP models: deepset/gbert",
    cloud:        "Event-driven architecture on AWS",
    backend:      "Backend scaling: horizontal vs vertical",
    data:         "Data architecture: medallion architecture",
    project:      "All projects: final documentation",
    mern:         "Save: visa + apartment deposit fund",
    german:       "Goethe C1 Exam (optional but powerful)",
    tools:        "Review: savings runway in Notion",
    sundayReview: "C1 exam registered?",
  },
  {
    week:         77,
    weekStart:    "24 Oct 2027",
    phase:        "Phase 7 \u2014 Senior Projects",
    ml:           "Build: German-language AI product (unique portfolio)",
    cloud:        "AWS Well-Architected review of all projects",
    backend:      "API design: OpenAPI 3.1 spec-first",
    data:         "Data architecture: Kappa vs Lambda",
    project:      "GitHub: ensure all repos public + pinned",
    mern:         "Save: built up relocation budget",
    german:       "German: daily maintenance 20 Anki + podcast",
    tools:        "Review: visa requirements checklist",
    sundayReview: "All 6 projects: GitHub stars growing?",
  },
  {
    week:         78,
    weekStart:    "31 Oct 2027",
    phase:        "Phase 7 \u2014 Senior Projects",
    ml:           "Submit to German AI conference / blog post",
    cloud:        "Contribute to Terraform registry module",
    backend:      "Technical blog: Java vs Kotlin in German enterprise",
    data:         "Write: data architecture decision blog",
    project:      "GitHub profile README: showcase projects",
    mern:         "Reduce freelance load: 10 hrs/week only",
    german:       "German: daily maintenance",
    tools:        "Review: Blue Card salary threshold clarity",
    sundayReview: "LinkedIn: 500+ connections?",
  },
  {
    week:         79,
    weekStart:    "07 Nov 2027",
    phase:        "Phase 7 \u2014 Senior Projects",
    ml:           "Revisit: all 6 projects \u2014 update READMEs",
    cloud:        "Blog: GDPR-compliant AWS architecture",
    backend:      "Open source: contribute to Spring ecosystem",
    data:         "Data portfolio final polish",
    project:      "LinkedIn: update with all projects + certs",
    mern:         "Maintain: 1\u20132 retainer clients",
    german:       "German: daily maintenance",
    tools:        "Review: target companies list (20 companies)",
    sundayReview: "XING: active in German tech groups?",
  },
  {
    week:         80,
    weekStart:    "14 Nov 2027",
    phase:        "Phase 7 \u2014 Senior Projects",
    ml:           "ML technical blog: write 2 articles",
    cloud:        "Blog: Kubernetes cost optimisation",
    backend:      "Backend portfolio: all projects documented",
    data:         "GitHub: all data projects pinned",
    project:      "Prepare interview project walk-through (30 min)",
    mern:         "MERN income: financial runway secured",
    german:       "German: daily maintenance",
    tools:        "Tools: Q1 2028 audit",
    sundayReview: "Financial runway: 6 months confirmed?",
  },
  {
    week:         81,
    weekStart:    "21 Nov 2027",
    phase:        "Phase 7 \u2014 Senior Projects",
    ml:           "Open source: submit PR to HuggingFace / LangChain",
    cloud:        "Cloud portfolio: all projects on Hetzner + AWS",
    backend:      "Mock: senior backend interview",
    data:         "Apply data engineering roles: 5 applications",
    project:      "Mock interview: present Project 1",
    mern:         "Freelance: wind down to 5 hrs/week",
    german:       "German: job interview practice auf Deutsch \u00d7 2",
    tools:        "Job hunt: Notion tracker \u2014 20 applications logged",
    sundayReview: "20 applications sent this week?",
  },
  {
    week:         82,
    weekStart:    "28 Nov 2027",
    phase:        "Phase 7 \u2014 Senior Projects",
    ml:           "Mock interviews: ML coding (Leetcode + ML)",
    cloud:        "Mock cloud interviews \u00d7 3",
    backend:      "Mock: system design at Bosch scale",
    data:         "Data interviews \u00d7 2",
    project:      "Mock interview: present Project 2",
    mern:         "Maintain: 1 retainer client during job hunt",
    german:       "German: job interview practice \u00d7 2",
    tools:        "Job hunt: interview feedback logged",
    sundayReview: "First interview feedback received?",
  },
  {
    week:         83,
    weekStart:    "05 Dec 2027",
    phase:        "Phase 8 \u2014 Specialise",
    ml:           "System design: ML infra at BMW / Bosch scale",
    cloud:        "Advanced: eBPF for ML workload observability",
    backend:      "Advanced system design: ML serving infrastructure",
    data:         "Advanced data + ML intersection",
    project:      "Mock interview: present Project 4 (LLM)",
    mern:         "Job hunt funded by savings + 1 retainer",
    german:       "German: company research in German",
    tools:        "Job hunt: referral pipeline tracked",
    sundayReview: "Mock ML system design \u00d7 3 done?",
  },
  {
    week:         84,
    weekStart:    "12 Dec 2027",
    phase:        "Phase 8 \u2014 Specialise",
    ml:           "Advanced: retrieval-augmented generation v2",
    cloud:        "Advanced: Kubernetes for ML (Kubeflow)",
    backend:      "Advanced: event mesh architecture",
    data:         "Final data project updates",
    project:      "Mock interview: present Project 3 (infra)",
    mern:         "MERN income: cover expenses during interviews",
    german:       "German: prepare German-language answers",
    tools:        "Job hunt: offer comparison matrix in Notion",
    sundayReview: "Offer comparison matrix started?",
  },
  {
    week:         85,
    weekStart:    "19 Dec 2027",
    phase:        "Phase 8 \u2014 Specialise",
    ml:           "Advanced: Constitutional AI concepts",
    cloud:        "Kubeflow pipelines for ML training",
    backend:      "Advanced: polyglot persistence patterns",
    data:         "Data engineering mock interview",
    project:      "Mock interview: present Projects 5+6 (data)",
    mern:         "Financial: calculate Germany relocation costs",
    german:       "German: salary negotiation phrases auf Deutsch",
    tools:        "Job hunt: negotiation notes in Obsidian",
    sundayReview: "Salary negotiation prepared?",
  },
  {
    week:         86,
    weekStart:    "26 Dec 2027",
    phase:        "Phase 8 \u2014 Specialise",
    ml:           "Study: recent ML papers (Arxiv weekly)",
    cloud:        "Cloud-native ML deployment patterns",
    backend:      "Revisit all projects: add observability",
    data:         "Review DP-203 + Azure certs",
    project:      "Mock interview: present OSS contributions",
    mern:         "Financial: Blue Card salary threshold (\u20ac45,552)",
    german:       "German: email templates auf Deutsch",
    tools:        "Job hunt: relocation checklist in Notion",
    sundayReview: "Visa checklist complete?",
  },
  {
    week:         87,
    weekStart:    "02 Jan 2028",
    phase:        "Phase 8 \u2014 Specialise",
    ml:           "Study: recent ML papers #2",
    cloud:        "Review: all cloud projects + update READMEs",
    backend:      "Revisit all projects: add integration tests",
    data:         "Prepare data architecture diagrams",
    project:      "Final portfolio review",
    mern:         "Financial: city comparison (Munich vs Berlin cost)",
    german:       "German: cover letter final review by native",
    tools:        "Job hunt: visa checklist in Notion",
    sundayReview: "Apartment search started?",
  },
  {
    week:         88,
    weekStart:    "09 Jan 2028",
    phase:        "Phase 8 \u2014 Specialise",
    ml:           "Build new mini-project from paper",
    cloud:        "Prepare cloud architecture diagrams for interviews",
    backend:      "Final code quality pass",
    data:         "Data engineering final prep",
    project:      "Final portfolio: all links working",
    mern:         "Financial: savings runway = 6 months",
    german:       "German: phone interview practice",
    tools:        "Job hunt: apartment checklist",
    sundayReview: "Banking + insurance researched?",
  },
  {
    week:         89,
    weekStart:    "16 Jan 2028",
    phase:        "Phase 8 \u2014 Specialise",
    ml:           "Technical writing: ADR for ML system",
    cloud:        "Review certs + renew if needed",
    backend:      "Prepare code samples for interviews",
    data:         "Applications: 10 data roles",
    project:      "Submit 10 targeted applications with tailored cover",
    mern:         "Freelance: fully wound down",
    german:       "German: interview day preparation",
    tools:        "Job hunt: banking checklist",
    sundayReview: "10 more applications sent?",
  },
  {
    week:         90,
    weekStart:    "23 Jan 2028",
    phase:        "Phase 8 \u2014 Specialise",
    ml:           "Portfolio review: update all projects + GitHub",
    cloud:        "Final infra polish",
    backend:      "Portfolio: GitHub pinned repos + READMEs",
    data:         "Technical interviews",
    project:      "Submit 10 more applications",
    mern:         "Freelance: final invoice sent",
    german:       "German: daily maintenance",
    tools:        "Job hunt: health insurance comparison",
    sundayReview: "Financial: all costs planned?",
  },
  {
    week:         91,
    weekStart:    "30 Jan 2028",
    phase:        "Phase 8 \u2014 Specialise",
    ml:           "Mock ML interviews \u00d7 3 this week",
    cloud:        "Target: German DevOps/Cloud roles applied",
    backend:      "Apply backend roles: 10 applications",
    data:         "Technical interviews",
    project:      "Follow up on all applications",
    mern:         "Focus 100%: job applications only",
    german:       "German: maintenance + interview",
    tools:        "Job hunt: tax setup checklist",
    sundayReview: "First-round interviews happening?",
  },
  {
    week:         92,
    weekStart:    "06 Feb 2028",
    phase:        "Phase 8 \u2014 Specialise",
    ml:           "Mock system design \u00d7 3 this week",
    cloud:        "Cloud interview prep: scenario questions",
    backend:      "Interview prep: Java Spring deep dive",
    data:         "Data system design interview",
    project:      "First-round interviews",
    mern:         "Focus 100%: interviews",
    german:       "German: maintenance + interview",
    tools:        "Job hunt: all logistics planned",
    sundayReview: "Technical interviews scheduled?",
  },
  {
    week:         93,
    weekStart:    "13 Feb 2028",
    phase:        "Phase 8 \u2014 Specialise",
    ml:           "Prepare HuggingFace profile + model cards",
    cloud:        "Cloud interview prep: cost + GDPR scenarios",
    backend:      "Interview prep: system design scenarios",
    data:         "Offer comparison",
    project:      "Technical interviews",
    mern:         "Focus 100%: interviews",
    german:       "German: maintenance + interview",
    tools:        "Job hunt: relocation budget confirmed",
    sundayReview: "Final interviews this week?",
  },
  {
    week:         94,
    weekStart:    "20 Feb 2028",
    phase:        "Phase 8 \u2014 Specialise",
    ml:           "Final portfolio polish",
    cloud:        "Cloud final review",
    backend:      "Interview: live coding practice",
    data:         "Offer negotiation",
    project:      "Final interviews",
    mern:         "Focus 100%: final interviews",
    german:       "German: maintenance + interview",
    tools:        "Job hunt: offer signed",
    sundayReview: "Offer received?",
  },
  {
    week:         95,
    weekStart:    "27 Feb 2028",
    phase:        "Phase 8 \u2014 Specialise",
    ml:           "Apply to German ML roles (10 applications)",
    cloud:        "Apply cloud roles \u2014 10 applications",
    backend:      "Applications + follow-up",
    data:         "Final prep",
    project:      "Offer + negotiation",
    mern:         "OFFER RECEIVED",
    german:       "German: celebrate \u2014 B2/C1 ACHIEVED",
    tools:        "Job hunt: paperwork submitted",
    sundayReview: "OFFER SIGNED \u2014 celebrate!",
  },
  {
    week:         96,
    weekStart:    "05 Mar 2028",
    phase:        "Phase 8 \u2014 Specialise",
    ml:           "Apply + follow up",
    cloud:        "Follow-up + LinkedIn outreach German engineers",
    backend:      "Technical interviews",
    data:         "Final prep",
    project:      "Offer signed",
    mern:         "Negotiate: \u20ac80\u2013100k+ salary",
    german:       "German: relocation vocabulary",
    tools:        "Job hunt: visa application in progress",
    sundayReview: "Visa applied?",
  },
  {
    week:         97,
    weekStart:    "12 Mar 2028",
    phase:        "Phase 9 \u2014 Job Hunt",
    ml:           "Interview prep: coding (daily Leetcode)",
    cloud:        "Interview: cloud architecture deep dive",
    backend:      "Technical interviews",
    data:         "Final prep",
    project:      "Visa / Blue Card application",
    mern:         "Sign contract",
    german:       "German: bureaucracy vocabulary (Anmeldung etc.)",
    tools:        "Relocation: apartment viewing scheduled",
    sundayReview: "Apartment found?",
  },
  {
    week:         98,
    weekStart:    "19 Mar 2028",
    phase:        "Phase 9 \u2014 Job Hunt",
    ml:           "Interview prep: ML concepts flashcards",
    cloud:        "Interview: K8s troubleshooting",
    backend:      "Technical interviews",
    data:         "Final prep",
    project:      "Relocation preparation",
    mern:         "Financial: relocation package negotiation",
    german:       "German: apartment hunting phrases",
    tools:        "Relocation: moving logistics",
    sundayReview: "Moving date set?",
  },
  {
    week:         99,
    weekStart:    "26 Mar 2028",
    phase:        "Phase 9 \u2014 Job Hunt",
    ml:           "Interview prep: system design",
    cloud:        "Interview: GDPR technical controls",
    backend:      "Offer evaluation",
    data:         "Offer accepted",
    project:      "Apartment search in target city",
    mern:         "Financial: first German payslip projection",
    german:       "German: banking / insurance vocabulary",
    tools:        "Relocation: utilities setup",
    sundayReview: "All logistics confirmed?",
  },
  {
    week:         100,
    weekStart:    "02 Apr 2028",
    phase:        "Phase 9 \u2014 Job Hunt",
    ml:           "Interview prep: behavioural (German culture)",
    cloud:        "Interview: cost optimisation scenarios",
    backend:      "Offer negotiation",
    data:         "Notice period",
    project:      "Language prep: workplace German",
    mern:         "Finances: set up German bank (N26/Deutsche Bank)",
    german:       "German: workplace day-1 preparation",
    tools:        "Relocation: German bank account open",
    sundayReview: "German bank account open?",
  },
  {
    week:         101,
    weekStart:    "09 Apr 2028",
    phase:        "Phase 9 \u2014 Job Hunt",
    ml:           "Final interviews",
    cloud:        "Final cloud interviews",
    backend:      "Paperwork + visa",
    data:         "Relocation prep",
    project:      "Final weeks in home country",
    mern:         "Register: Anmeldung (address registration)",
    german:       "German: final review \u2014 conversational fluency",
    tools:        "Relocation: health insurance signed",
    sundayReview: "Health insurance signed?",
  },
  {
    week:         102,
    weekStart:    "16 Apr 2028",
    phase:        "Phase 9 \u2014 Job Hunt",
    ml:           "Final interviews",
    cloud:        "Offer evaluation",
    backend:      "Relocation prep",
    data:         "Relocation prep",
    project:      "Move to Germany",
    mern:         "Setup: German health insurance (TK/AOK)",
    german:       "German: daily use in Germany BEGINS",
    tools:        "Day 1 prep: commute, dress code, team research",
    sundayReview: "In Germany \u2014 Anmeldung done?",
  },
  {
    week:         103,
    weekStart:    "23 Apr 2028",
    phase:        "Phase 9 \u2014 Job Hunt",
    ml:           "Negotiate offer / Visa prep",
    cloud:        "Offer negotiation",
    backend:      "Notice period start",
    data:         "Final week",
    project:      "Onboarding prep",
    mern:         "Setup: tax number + Steuerklasse",
    german:       "German: immersion mode",
    tools:        "Day 1 prep: first 30-60-90 day plan written",
    sundayReview: "Day 1 plan written?",
  },
  {
    week:         104,
    weekStart:    "30 Apr 2028",
    phase:        "Phase 9 \u2014 Job Hunt",
    ml:           "START \u2014 Top 0.1% achieved",
    cloud:        "HIRED",
    backend:      "START at German company",
    data:         "START",
    project:      "DAY 1 at German company \u2014 TOP 0.1% ACHIEVED",
    mern:         "FINANCIAL FREEDOM \u2014 German salary + savings",
    german:       "German: FLUENT \u2014 B2/C1 \u2014 massive career advantage",
    tools:        "DONE \u2014 all tools served their purpose",
    sundayReview: "TOP 0.1% \u2014 DONE. You made it.",
  },
]

export const ROADMAP_MILESTONES: ExcelMilestone[] = [
  {
    title:      "4th semester exams DONE. Arabic learning complete.",
    targetWeek: "Week 8",
    targetDate: "1 Jul 2026",
    category:   "Life",
    why:        "Full 3\u20134 hrs/day now available for learning",
  },
  {
    title:      "Project 1 PUBLISHED \u2014 GDPR-RAG chatbot on GitHub",
    targetWeek: "Week 10",
    targetDate: "13 Jul 2026",
    category:   "Portfolio",
    why:        "First portfolio proof of concept",
  },
  {
    title:      "Project 2 PUBLISHED \u2014 Predictive maintenance on AWS",
    targetWeek: "Week 16",
    targetDate: "24 Aug 2026",
    category:   "Portfolio",
    why:        "Industrial ML = German employer magnet",
  },
  {
    title:      "Project 3 PUBLISHED \u2014 Multi-tenant SaaS on EKS",
    targetWeek: "Week 22",
    targetDate: "5 Oct 2026",
    category:   "Portfolio",
    why:        "Cloud infra project proves DevOps skills",
  },
  {
    title:      "Project 5 PUBLISHED \u2014 EV charging data pipeline",
    targetWeek: "Week 27",
    targetDate: "9 Nov 2026",
    category:   "Portfolio",
    why:        "Data engineering portfolio piece",
  },
  {
    title:      "Project 4 PUBLISHED \u2014 LLM fine-tune on HuggingFace",
    targetWeek: "Week 32",
    targetDate: "14 Dec 2026",
    category:   "Portfolio",
    why:        "LLM project = top 1% differentiation",
  },
  {
    title:      "Project 6 PUBLISHED \u2014 GDPR data platform",
    targetWeek: "Week 37",
    targetDate: "18 Jan 2027",
    category:   "Portfolio",
    why:        "ALL 6 PROJECTS DONE \u2014 portfolio complete",
  },
  {
    title:      "AWS Solutions Architect Associate (SAA-C03) PASSED",
    targetWeek: "Week 32",
    targetDate: "14 Dec 2026",
    category:   "Certification",
    why:        "Germany's most-valued cloud cert",
  },
  {
    title:      "Azure AZ-104 PASSED",
    targetWeek: "Week 40",
    targetDate: "15 Feb 2027",
    category:   "Certification",
    why:        "German enterprise Azure shops",
  },
  {
    title:      "CKA (Kubernetes) PASSED",
    targetWeek: "Week 46",
    targetDate: "29 Mar 2027",
    category:   "Certification",
    why:        "K8s = must-have for DevOps roles",
  },
  {
    title:      "Azure DP-203 Data Engineer PASSED",
    targetWeek: "Week 42",
    targetDate: "1 Mar 2027",
    category:   "Certification",
    why:        "Data engineering credential",
  },
  {
    title:      "Goethe B1 German Exam PASSED",
    targetWeek: "Week 33",
    targetDate: "21 Dec 2026",
    category:   "German",
    why:        "Opens Mittelstand doors",
  },
  {
    title:      "Goethe B2 German Exam PASSED",
    targetWeek: "Week 44",
    targetDate: "15 Mar 2027",
    category:   "German",
    why:        "Salary multiplier \u2014 very few expats reach B2",
  },
  {
    title:      "Goethe C1 German Exam PASSED (optional)",
    targetWeek: "Week 76",
    targetDate: "25 Oct 2027",
    category:   "German",
    why:        "Elite tier \u2014 almost no expat engineers reach C1",
  },
  {
    title:      "MERN freelance: $1000/month reached",
    targetWeek: "Week 40",
    targetDate: "15 Feb 2027",
    category:   "Finance",
    why:        "Journey is financially self-funded",
  },
  {
    title:      "MERN freelance: \u20ac2000/month reached",
    targetWeek: "Week 57",
    targetDate: "14 Jun 2027",
    category:   "Finance",
    why:        "Relocation savings accumulating",
  },
  {
    title:      "Relocation savings: \u20ac5000 saved",
    targetWeek: "Week 75",
    targetDate: "25 Oct 2027",
    category:   "Finance",
    why:        "Covers visa + apartment deposit + flights",
  },
  {
    title:      "OSS first PR merged",
    targetWeek: "Week 38",
    targetDate: "1 Feb 2027",
    category:   "Portfolio",
    why:        "Open source = trust signal for German employers",
  },
  {
    title:      "Personal portfolio site live",
    targetWeek: "Week 45",
    targetDate: "22 Mar 2027",
    category:   "Portfolio",
    why:        "Professional online presence",
  },
  {
    title:      "Technical blog: 3 posts published",
    targetWeek: "Week 50",
    targetDate: "26 Apr 2027",
    category:   "Portfolio",
    why:        "Thought leadership",
  },
  {
    title:      "LinkedIn: 500+ connections (German tech)",
    targetWeek: "Week 70",
    targetDate: "13 Sep 2027",
    category:   "Network",
    why:        "German referral network activated",
  },
  {
    title:      "XING profile active in German tech groups",
    targetWeek: "Week 36",
    targetDate: "18 Jan 2027",
    category:   "Network",
    why:        "German-specific professional presence",
  },
  {
    title:      "Mock system design interviews \u00d7 10 done",
    targetWeek: "Week 82",
    targetDate: "5 Jan 2028",
    category:   "Interview",
    why:        "Prepared for senior German interviews",
  },
  {
    title:      "30 job applications sent to German companies",
    targetWeek: "Week 90",
    targetDate: "2 Mar 2028",
    category:   "Job Hunt",
    why:        "Numbers game \u2014 need pipeline",
  },
  {
    title:      "First German technical interview",
    targetWeek: "Week 92",
    targetDate: "16 Mar 2028",
    category:   "Job Hunt",
    why:        "Validation of all work",
  },
  {
    title:      "Offer received from German company",
    targetWeek: "Week 95",
    targetDate: "6 Apr 2028",
    category:   "Job Hunt",
    why:        "The goal",
  },
  {
    title:      "Offer signed \u2014 \u20ac80\u2013100k+ salary",
    targetWeek: "Week 96",
    targetDate: "13 Apr 2028",
    category:   "Job Hunt",
    why:        "Top 0.1% salary in Germany for your background",
  },
  {
    title:      "Blue Card visa application submitted",
    targetWeek: "Week 97",
    targetDate: "20 Apr 2028",
    category:   "Relocation",
    why:        "Legal right to work in Germany",
  },
  {
    title:      "Moved to Germany",
    targetWeek: "Week 102",
    targetDate: "25 May 2028",
    category:   "Relocation",
    why:        "Phase complete",
  },
  {
    title:      "DAY 1 at German tech company \u2014 TOP 0.1% ACHIEVED",
    targetWeek: "Week 104",
    targetDate: "10 May 2028",
    category:   "GOAL",
    why:        "You made it",
  },
]


const TRACK_MAP: Partial<Record<keyof ExcelWeek, TaskTrack>> = {
  ml: 'ML', cloud: 'Cloud', backend: 'Backend',
  data: 'Data', project: 'Project', german: 'German', mern: 'MERN',
}

const PRIORITY_MAP: Partial<Record<keyof ExcelWeek, 'High'|'Medium'|'Low'>> = {
  ml: 'High', project: 'High', cloud: 'Medium',
  backend: 'Medium', data: 'Medium', german: 'Medium', mern: 'Medium',
}

const HOURS_MAP: Partial<Record<keyof ExcelWeek, number>> = {
  ml: 1.5, project: 2, cloud: 1.5, backend: 1, data: 1, german: 0.5, mern: 0.5,
}


const EMPTY_VALS = new Set(['', '\u2014', '\u2014', '-', '\u2013'])

function isEmpty(val: string): boolean {
  if (!val) return true
  const trimmed = val.trim()
  if (EMPTY_VALS.has(trimmed)) return true
  if (trimmed.startsWith('\u2014') || trimmed.startsWith('\u2013') || trimmed.startsWith('-')) return true
  return false
}

// Daily rotation: each track appears on specific days so no repeats
// Sun: german+mern  Mon: ml  Tue: project+backend  Wed: cloud+data
// Thu: project+ml   Fri: german+mern  Sat: cloud+backend+data (deep sprint)
const DAY_SCHEDULE: Record<number, Array<keyof ExcelWeek>> = {
  0: ['german', 'mern'],
  1: ['ml'],
  2: ['project', 'backend'],
  3: ['cloud', 'data'],
  4: ['project', 'ml'],
  5: ['german', 'mern'],
  6: ['cloud', 'backend', 'data'],
}

export interface SeedTask {
  title:    string
  track:    TaskTrack
  priority: 'High' | 'Medium' | 'Low'
  hours:    number
  notes:    string
}

export function getDailyTasksFromRoadmap(weekNum: number, dayOfWeek: number): SeedTask[] {
  const week = ROADMAP_WEEKS.find(w => w.week === weekNum)
  if (!week) return []

  const tasks: SeedTask[] = []
  const todayKeys = DAY_SCHEDULE[dayOfWeek] ?? ['ml']

  for (const key of todayKeys) {
    const val = week[key] as string
    if (!val || isEmpty(val)) continue
    const track = TRACK_MAP[key]
    if (!track) continue
    tasks.push({
      title:    val,
      track,
      priority: PRIORITY_MAP[key] ?? 'Medium',
      hours:    HOURS_MAP[key]    ?? 1,
      notes:    week.phase,
    })
  }

  // Monday only: add tools habit reminder
  if (dayOfWeek === 1 && week.tools && !isEmpty(week.tools)) {
    tasks.push({
      title:    'Tools this week: ' + week.tools,
      track:    'ML',
      priority: 'Low',
      hours:    0.5,
      notes:    'Set up your daily tools habit for this week',
    })
  }

  // Sunday: add weekly review goal
  if (dayOfWeek === 0 && week.sundayReview && !isEmpty(week.sundayReview)) {
    tasks.push({
      title:    'Weekly review: ' + week.sundayReview,
      track:    'ML',
      priority: 'High',
      hours:    0.5,
      notes:    week.phase,
    })
  }

  // Fallback: if today's scheduled tracks are all empty in Excel (early weeks),
  // pull the first non-empty track so the day is never blank
  if (tasks.length === 0) {
    const allKeys: Array<keyof ExcelWeek> = ['ml','cloud','german','mern','data','backend','project']
    for (const key of allKeys) {
      const val = week[key] as string
      if (!val || isEmpty(val)) continue
      const track = TRACK_MAP[key]
      if (!track) continue
      tasks.push({
        title:    val,
        track,
        priority: PRIORITY_MAP[key] ?? 'Medium',
        hours:    HOURS_MAP[key]    ?? 1,
        notes:    week.phase,
      })
      break
    }
  }

  return tasks
}